#!/usr/bin/env python
import os, sys, inspect, utils
from os import path

Import('build')

Env = build.env.Clone()
Env.Append(CPPDEFINES=('KROLL_FALCON_API_EXPORT', 1))
build.add_thirdparty(Env, 'poco')

if build.is_osx():
	Env.Append(CPPPATH=['/usr/lib', '/usr/include'])
	Env.Append(LIBS=['falcon_engine'])

elif build.is_linux():
	Env.Append(LIBS=['falcon_engine'])

elif build.is_win32():
	falcon_inc = os.environ['FALCON_INC_PATH']
	falcon_lib = os.environ['FALCON_LIB_PATH']
	Env.Append(CPPPATH=[falcon_inc,build.kroll_include_dir])
	Env.Append(LIBPATH=[falcon_lib])
	Env.Append(LIBS=['falcon_engine'])
	Env.Append(CCFLAGS = ['/MD'])

m = build.add_module('falcon', env=Env)
t = Env.SharedLibrary(m.build_dir + '/falconmodule', Glob('*.cpp'))
build.mark_build_target(t)
