#!/usr/bin/env python
import os, sys, inspect, utils
from os import path

Import('build')

Env = build.env.Clone()
Env.Append(CPPDEFINES=('KROLL_FALCON_API_EXPORT', 1))
build.add_thirdparty(Env, 'poco')

if build.is_osx():
	# TODO
    pass

elif build.is_linux():
    Env.Append(LIBS=['falcon_engine'])

elif build.is_win32():
	# TODO
    pass

m = build.add_module('falcon', env=Env)
t = Env.SharedLibrary(m.build_dir + '/falconmodule', Glob('*.cpp'))
build.mark_build_target(t)
